### ISSUE TITLE
Could not initialize class play.api.http.DefaultHttpErrorHandler

### ISSUE THREAD

**Issue by mvexel** [maproulette/maproulette2#33]
Since updating to the latest code, I get the following error on first invocation:

```
[error] p.c.s.n.PlayRequestHandler - Exception caught in Netty
java.lang.NoClassDefFoundError: Could not initialize class play.api.http.DefaultHttpErrorHandler$
	at play.core.server.Server$class.logExceptionAndGetResult$1(Server.scala:45)
	at play.core.server.Server$class.getHandlerFor(Server.scala:65)
	at play.core.server.NettyServer.getHandlerFor(NettyServer.scala:47)
	at play.core.server.netty.PlayRequestHandler.handle(PlayRequestHandler.scala:82)
	at play.core.server.netty.PlayRequestHandler.channelRead(PlayRequestHandler.scala:163)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:292)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:278)
	at com.typesafe.netty.http.HttpStreamsHandler.channelRead(HttpStreamsHandler.java:129)
	at com.typesafe.netty.http.HttpStreamsServerHandler.channelRead(HttpStreamsServerHandler.java:96)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:292)
```

**Comment by mvexel** [comment]
Seems to me there is another issue hidden behind this, but I had not seen this before either.

**Comment by mgcuthbert** [comment]
This seemed to be introduced when I updated the Play framework to 2.5.3. I am not 100% as to why, I am guessing there are some conflicts in the libraries that we are using. Either way I downgraded back to 2.5.0 (wasn't using anything in particular in 2.5.3). So you can test again and see if it resolves the issue.

**Comment by mgcuthbert** [comment]
Closing this issue, after downgrade it seems to have gone away.
